groups:
  - name: vm-alerts
    rules:
      # CPU Usage Alert
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      # Memory Usage Alert
      - alert: HighMemoryUsage
        expr: 100 * (1 - ((node_memory_MemAvailable_bytes or node_memory_MemFree_bytes) / node_memory_MemTotal_bytes)) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # Disk Space Alert
      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 90% for more than 5 minutes on {{ $labels.instance }} device {{ $labels.device }}"

      # Load Average Alert
      - alert: HighLoadAverage
        expr: node_load1 > 4
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High load average detected"
          description: "Load average is above 4 for more than 5 minutes on {{ $labels.instance }}"

      # Service Down Alert
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} service is down on {{ $labels.instance }}"

      # Network Interface Down
      - alert: NetworkInterfaceDown
        expr: node_network_up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Network interface is down"
          description: "Network interface {{ $labels.device }} is down on {{ $labels.instance }}"

      # Service Down (Blackbox)
      - alert: ServiceDown
        expr: probe_success{job="blackbox"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "Service {{ $labels.instance }} is down (blackbox probe failed)"

      # High Response Time
      - alert: HighResponseTime
        expr: probe_duration_seconds{job="blackbox"} > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "Service {{ $labels.instance }} has high response time: {{ $value }}s"

      # HTTP Error Status
      - alert: HTTPErrorStatus
        expr: probe_http_status_code{job="blackbox"} >= 400
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "HTTP error status detected"
          description: "Service {{ $labels.instance }} returned HTTP {{ $value }}"
